server:
  port: 8086

spring:
  application:
    name: product
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  data:
    mongodb:
      database: ecommerce
      username: admin
      password: admin
      authentication-database: admin
      port: 27018
      host: localhost
      auto-index-creation: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

  output:
    ansi:
      enabled: always

ecommerce:
  broker:
    exchange:
      orderProductCommand: order-product
    queue:
      orderProductRequest: order-product-request
    key:
      bindOrderProductRequestCommand: order-product-request
      bindOrderProductReplyCommand: order-product-reply
